//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace templateApp.GUI.Modulo16 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M16_Recursointerfaz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M16_Recursointerfaz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("templateApp.GUI.Modulo16.M16_Recursointerfaz", typeof(M16_Recursointerfaz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string ABRIR_TD {
            get {
                return ResourceManager.GetString("ABRIR_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=.
        /// </summary>
        internal static string ABRIR_TR {
            get {
                return ResourceManager.GetString("ABRIR_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=E-.
        /// </summary>
        internal static string ABRIR_TR_EVENTO {
            get {
                return ResourceManager.GetString("ABRIR_TR_EVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=I-.
        /// </summary>
        internal static string ABRIR_TR_INVENTARIO {
            get {
                return ResourceManager.GetString("ABRIR_TR_INVENTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=M-.
        /// </summary>
        internal static string ABRIR_TR_MATRICULA {
            get {
                return ResourceManager.GetString("ABRIR_TR_MATRICULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;M16_ConsultarMensualidad.aspx?compAgregar=.
        /// </summary>
        internal static string BOTON_AGREGAR_CARRITO {
            get {
                return ResourceManager.GetString("BOTON_AGREGAR_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-success glyphicon glyphicon-shopping-cart&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot;  onclick=&quot;prueba3(this);&quot; id=&quot;.
        /// </summary>
        internal static string BOTON_AGREGAR_EVENTO_CARRITO {
            get {
                return ResourceManager.GetString("BOTON_AGREGAR_EVENTO_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-success glyphicon glyphicon-shopping-cart&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot;  onclick=&quot;prueba3(this);&quot; id=&quot;.
        /// </summary>
        internal static string BOTON_AGREGAR_IMPLEMENTO_CARRITO_2 {
            get {
                return ResourceManager.GetString("BOTON_AGREGAR_IMPLEMENTO_CARRITO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-success glyphicon glyphicon-shopping-cart&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot;  onclick=&quot;prueba3(this);&quot; id=&quot;.
        /// </summary>
        internal static string BOTON_AGREGAR_MATRICULA_CARRITO {
            get {
                return ResourceManager.GetString("BOTON_AGREGAR_MATRICULA_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BOTON_CERRAR {
            get {
                return ResourceManager.GetString("BOTON_CERRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BOTON_CERRAR_IMPLEMENTO_CARRITO_2 {
            get {
                return ResourceManager.GetString("BOTON_CERRAR_IMPLEMENTO_CARRITO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;M12_ListarCompetencias.aspx?compEliminar=.
        /// </summary>
        internal static string BOTON_ELIMINAR {
            get {
                return ResourceManager.GetString("BOTON_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;M16_VerCarrito?accion=3&amp;item=3&amp;id=.
        /// </summary>
        internal static string BOTON_ELIMINAR_ACCION_EVENTO {
            get {
                return ResourceManager.GetString("BOTON_ELIMINAR_ACCION_EVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;M16_VerCarrito?accion=3&amp;item=1&amp;id=.
        /// </summary>
        internal static string BOTON_ELIMINAR_ACCION_IMPLEMENTO {
            get {
                return ResourceManager.GetString("BOTON_ELIMINAR_ACCION_IMPLEMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;M16_VerCarrito?accion=3&amp;item=2&amp;id=.
        /// </summary>
        internal static string BOTON_ELIMINAR_ACCION_MATRICULA {
            get {
                return ResourceManager.GetString("BOTON_ELIMINAR_ACCION_MATRICULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; onclick=&quot;prueba3(this);&quot; id=&quot;.
        /// </summary>
        internal static string BOTON_ELIMINAR_GENERAL {
            get {
                return ResourceManager.GetString("BOTON_ELIMINAR_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-primary glyphicon glyphicon glyphicon-print&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot;  onclick=&quot;prueba3(this);&quot; id=&quot;.
        /// </summary>
        internal static string BOTON_IMPRIMIR_FACTURA {
            get {
                return ResourceManager.GetString("BOTON_IMPRIMIR_FACTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;M12_ListarCompetencias.aspx?compDetalle=.
        /// </summary>
        internal static string BOTON_INFO {
            get {
                return ResourceManager.GetString("BOTON_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot;   data-toggle=&quot;modal&quot; data-target=&quot;#modal-info1&quot;  id=&quot;.
        /// </summary>
        internal static string BOTON_INFO_EVENTO {
            get {
                return ResourceManager.GetString("BOTON_INFO_EVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot;   data-toggle=&quot;modal&quot; data-target=&quot;#modal-info2&quot;  id=&quot;.
        /// </summary>
        internal static string BOTON_INFO_EVENTO_CARRITO {
            get {
                return ResourceManager.GetString("BOTON_INFO_EVENTO_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot;   data-toggle=&quot;modal&quot; data-target=&quot;#modal-info1&quot;  id=&quot;.
        /// </summary>
        internal static string BOTON_INFO_PRODUCTO {
            get {
                return ResourceManager.GetString("BOTON_INFO_PRODUCTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-default glyphicon glyphicon-pencil&quot; href=&quot;M12_ModificarCompetencias.aspx?compMod=.
        /// </summary>
        internal static string BOTON_MODIFICAR {
            get {
                return ResourceManager.GetString("BOTON_MODIFICAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&gt;&lt;option value=1&gt;1&lt;/option&gt;&lt;option value=2&gt;2&lt;/option&gt;&lt;option value=3&gt;3&lt;/option&gt;&lt;option value=4&gt;4&lt;/option&gt;&lt;option value=5&gt;5&lt;/option&gt;&lt;option value=6&gt;6&lt;/option&gt;&lt;option value=7&gt;7&lt;/option&gt;&lt;option value=8&gt;8&lt;/option&gt;&lt;option value=9&gt;9&lt;/option&gt;&lt;option value=10&gt;10&lt;/option&gt;
        ///&lt;/select&gt;.
        /// </summary>
        internal static string CERRAR_COMBO {
            get {
                return ResourceManager.GetString("CERRAR_COMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        internal static string CERRAR_TD {
            get {
                return ResourceManager.GetString("CERRAR_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string CERRAR_TR {
            get {
                return ResourceManager.GetString("CERRAR_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_09.
        /// </summary>
        internal static string CODIGO_HTTP_EXCEPTION {
            get {
                return ResourceManager.GetString("CODIGO_HTTP_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_10.
        /// </summary>
        internal static string CODIGO_REFERENCIA_NULA_EXCEPTION {
            get {
                return ResourceManager.GetString("CODIGO_REFERENCIA_NULA_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;select   id=&apos;.
        /// </summary>
        internal static string COMBOCANTIDAD {
            get {
                return ResourceManager.GetString("COMBOCANTIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresando al metodo.
        /// </summary>
        internal static string MENSAJE_ENTRADA_LOGGER {
            get {
                return ResourceManager.GetString("MENSAJE_ENTRADA_LOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al interacturar con un componente HTTP.
        /// </summary>
        internal static string MENSAJE_HTTP_EXCEPTION {
            get {
                return ResourceManager.GetString("MENSAJE_HTTP_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al ingrear en un atributo en null.
        /// </summary>
        internal static string MENSAJE_REFERENCIA_NULA_EXCEPTION {
            get {
                return ResourceManager.GetString("MENSAJE_REFERENCIA_NULA_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saliendo del metodo.
        /// </summary>
        internal static string MENSAJE_SALIDA_LOGGER {
            get {
                return ResourceManager.GetString("MENSAJE_SALIDA_LOGGER", resourceCulture);
            }
        }
    }
}
