//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.DAO {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoGeneralDAO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoGeneralDAO() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.DAO.RecursoGeneralDAO", typeof(RecursoGeneralDAO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SKD_00_001.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_00_001.
        /// </summary>
        internal static string Codigo_Error_BaseDatos {
            get {
                return ResourceManager.GetString("Codigo_Error_BaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_00_003.
        /// </summary>
        internal static string Codigo_Error_Desconexion {
            get {
                return ResourceManager.GetString("Codigo_Error_Desconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_00_02.
        /// </summary>
        internal static string Codigo_Parametro_Errado {
            get {
                return ResourceManager.GetString("Codigo_Parametro_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con la Conexion en la Base de Datos, no se pudo abrir la conexion.
        /// </summary>
        internal static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con la Conexion en la BaseDeDatosSKD, no se pudo abrir la conexion.
        /// </summary>
        internal static string Mensaje_Error_BaseDatos {
            get {
                return ResourceManager.GetString("Mensaje_Error_BaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al Desconectarse con la BaseDeDatosSKD.
        /// </summary>
        internal static string Mensaje_Error_Desconexion {
            get {
                return ResourceManager.GetString("Mensaje_Error_Desconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en un parametro del stored procedure.
        /// </summary>
        internal static string Mensaje_Parametro_Errado {
            get {
                return ResourceManager.GetString("Mensaje_Parametro_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BaseDeDatosSKD.
        /// </summary>
        internal static string Nombre_Base_Datos {
            get {
                return ResourceManager.GetString("Nombre_Base_Datos", resourceCulture);
            }
        }
    }
}
