//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace templateApp.GUI.Master {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosInterfazMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosInterfazMaster() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("templateApp.GUI.Master.RecursosInterfazMaster", typeof(RecursosInterfazMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://.
        /// </summary>
        internal static string AliasHttp {
            get {
                return ResourceManager.GetString("AliasHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/GUI/Master/Inicio.aspx.
        /// </summary>
        internal static string direccionMaster_Inicio {
            get {
                return ResourceManager.GetString("direccionMaster_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/GUI/Master/menuLateral.xml.
        /// </summary>
        internal static string direccionMaster_MenuLateral {
            get {
                return ResourceManager.GetString("direccionMaster_MenuLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/GUI/Master/menuSuperior.xml.
        /// </summary>
        internal static string direccionMaster_MenuSuperior {
            get {
                return ResourceManager.GetString("direccionMaster_MenuSuperior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atleta.
        /// </summary>
        internal static string rolAtleta {
            get {
                return ResourceManager.GetString("rolAtleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atleta(Menor).
        /// </summary>
        internal static string rolAtletaMenor {
            get {
                return ResourceManager.GetString("rolAtletaMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dojo.
        /// </summary>
        internal static string rolDojo {
            get {
                return ResourceManager.GetString("rolDojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organizacion.
        /// </summary>
        internal static string rolOrganizacion {
            get {
                return ResourceManager.GetString("rolOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Representante.
        /// </summary>
        internal static string rolRepresentante {
            get {
                return ResourceManager.GetString("rolRepresentante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        internal static string rolSistema {
            get {
                return ResourceManager.GetString("rolSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a imagen.
        /// </summary>
        internal static string sessionImagen {
            get {
                return ResourceManager.GetString("sessionImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a logout.
        /// </summary>
        internal static string sessionLogout {
            get {
                return ResourceManager.GetString("sessionLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombreDePila.
        /// </summary>
        internal static string sessionNombreCompleto {
            get {
                return ResourceManager.GetString("sessionNombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rol.
        /// </summary>
        internal static string sessionRol {
            get {
                return ResourceManager.GetString("sessionRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a roles.
        /// </summary>
        internal static string sessionRoles {
            get {
                return ResourceManager.GetString("sessionRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuarioID.
        /// </summary>
        internal static string sessionUsuarioID {
            get {
                return ResourceManager.GetString("sessionUsuarioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string sessionUsuarioNombre {
            get {
                return ResourceManager.GetString("sessionUsuarioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -.
        /// </summary>
        internal static string splitRoles {
            get {
                return ResourceManager.GetString("splitRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string tagId {
            get {
                return ResourceManager.GetString("tagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a link.
        /// </summary>
        internal static string tagLink {
            get {
                return ResourceManager.GetString("tagLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string tagName {
            get {
                return ResourceManager.GetString("tagName", resourceCulture);
            }
        }
    }
}
