//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace templateApp.GUI.Modulo1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosInterfazModulo1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosInterfazModulo1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("templateApp.GUI.Modulo1.RecursosInterfazModulo1", typeof(RecursosInterfazModulo1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/GUI/Modulo1/Index.aspx.
        /// </summary>
        internal static string direccionM1_Index {
            get {
                return ResourceManager.GetString("direccionM1_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Atención! Se introdujo una secuencia de caracteres no permitidos..
        /// </summary>
        internal static string logCadenaMaliciosa {
            get {
                return ResourceManager.GetString("logCadenaMaliciosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se introdujo carácteres no validos (&gt;&lt;*-+¡?=(/&amp;%$·&quot;!) verifíque y vuelva a ingresar..
        /// </summary>
        internal static string logCaracterInvalidos {
            get {
                return ResourceManager.GetString("logCaracterInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña y/o usuario incorrecto..
        /// </summary>
        internal static string logErr {
            get {
                return ResourceManager.GetString("logErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su enlace ha caducado por favor vuelva a solicitar el reestablecimiento de su contraseña.
        /// </summary>
        internal static string logErrRestablecer {
            get {
                return ResourceManager.GetString("logErrRestablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Correo enviado!.
        /// </summary>
        internal static string logInfo {
            get {
                return ResourceManager.GetString("logInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string logRestablecerRequerimientos {
            get {
                return ResourceManager.GetString("logRestablecerRequerimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se reestableció con exito su contraseña.
        /// </summary>
        internal static string logSuccess {
            get {
                return ResourceManager.GetString("logSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡El correo no se encuentra registrado en SA-KARATEDO!.
        /// </summary>
        internal static string logWarning {
            get {
                return ResourceManager.GetString("logWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string parametroURLCorreoEnviado {
            get {
                return ResourceManager.GetString("parametroURLCorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string parametroURLCorreoFalla {
            get {
                return ResourceManager.GetString("parametroURLCorreoFalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string parametroURLID {
            get {
                return ResourceManager.GetString("parametroURLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string parametroURLReestablecerExito {
            get {
                return ResourceManager.GetString("parametroURLReestablecerExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string parametroURLReestablecerFalla {
            get {
                return ResourceManager.GetString("parametroURLReestablecerFalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caducado.
        /// </summary>
        internal static string parametroURLRestablecerCaducado {
            get {
                return ResourceManager.GetString("parametroURLRestablecerCaducado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string signoIgual {
            get {
                return ResourceManager.GetString("signoIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string signoPregunta {
            get {
                return ResourceManager.GetString("signoPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string tipoErr {
            get {
                return ResourceManager.GetString("tipoErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string tipoErrMalicioso {
            get {
                return ResourceManager.GetString("tipoErrMalicioso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string tipoInfo {
            get {
                return ResourceManager.GetString("tipoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string tipoSucess {
            get {
                return ResourceManager.GetString("tipoSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string tipoWarning {
            get {
                return ResourceManager.GetString("tipoWarning", resourceCulture);
            }
        }
    }
}
