//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.DAO.Modulo16 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo16 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo16() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.DAO.Modulo16.RecursosBDModulo16", typeof(RecursosBDModulo16).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costoMatricula.
        /// </summary>
        internal static string aliasCostomatricula {
            get {
                return ResourceManager.GetString("aliasCostomatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaInicio.
        /// </summary>
        internal static string aliasFechainicio {
            get {
                return ResourceManager.GetString("aliasFechainicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaTope.
        /// </summary>
        internal static string aliasFechatope {
            get {
                return ResourceManager.GetString("aliasFechatope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idIdentificadorMatricla.
        /// </summary>
        internal static string aliasIdentificadorMatricula {
            get {
                return ResourceManager.GetString("aliasIdentificadorMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idEvento.
        /// </summary>
        internal static string AliasIdEvento {
            get {
                return ResourceManager.GetString("AliasIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idModalidad.
        /// </summary>
        internal static string aliasIdmodalidad {
            get {
                return ResourceManager.GetString("aliasIdmodalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idOrganizacion.
        /// </summary>
        internal static string AliasidOrganizacion {
            get {
                return ResourceManager.GetString("AliasidOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreEvento.
        /// </summary>
        internal static string AliasNombreEvento {
            get {
                return ResourceManager.GetString("AliasNombreEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreModaliad.
        /// </summary>
        internal static string aliasNombremodalidad {
            get {
                return ResourceManager.GetString("aliasNombremodalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_06.
        /// </summary>
        internal static string CODIGO_EXCEPCION_ARGUMENTO_NULO {
            get {
                return ResourceManager.GetString("CODIGO_EXCEPCION_ARGUMENTO_NULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_07.
        /// </summary>
        internal static string CODIGO_EXCEPCION_FORMATO_INVALIDO {
            get {
                return ResourceManager.GetString("CODIGO_EXCEPCION_FORMATO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_01.
        /// </summary>
        internal static string CODIGO_EXCEPCION_GENERICO {
            get {
                return ResourceManager.GetString("CODIGO_EXCEPCION_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_08.
        /// </summary>
        internal static string CODIGO_EXCEPCION_SOBRECARGA {
            get {
                return ResourceManager.GetString("CODIGO_EXCEPCION_SOBRECARGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_05.
        /// </summary>
        internal static string Codigo_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_03.
        /// </summary>
        internal static string Codigo_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_05.
        /// </summary>
        internal static string Codigo_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_04.
        /// </summary>
        internal static string Codigo_ExcepcionParametro {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_02.
        /// </summary>
        internal static string Codigo_ExcepcionSql {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_CONSULTARCOMPRA.
        /// </summary>
        internal static string CONSULTAR_COMPRAS {
            get {
                return ResourceManager.GetString("CONSULTAR_COMPRAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_CONSULTAREVENTOS.
        /// </summary>
        internal static string CONSULTAR_EVENTOS {
            get {
                return ResourceManager.GetString("CONSULTAR_EVENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_CONSULTARINVENTARIO.
        /// </summary>
        internal static string CONSULTAR_IMPLEMENTOS {
            get {
                return ResourceManager.GetString("CONSULTAR_IMPLEMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_DETALLAREVENTO.
        /// </summary>
        internal static string DETALLAR_EVENTO {
            get {
                return ResourceManager.GetString("DETALLAR_EVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_DETALLARIMPLEMENTO.
        /// </summary>
        internal static string DETALLAR_IMPLEMENTO {
            get {
                return ResourceManager.GetString("DETALLAR_IMPLEMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uno de los parametros no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje__ExcepcionParametro {
            get {
                return ResourceManager.GetString("Mensaje__ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresando al metodo.
        /// </summary>
        internal static string MENSAJE_ENTRADA_LOGGER {
            get {
                return ResourceManager.GetString("MENSAJE_ENTRADA_LOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en parsear un atributo nulo.
        /// </summary>
        internal static string MENSAJE_EXCEPCION_ARGUMENTO_NULO {
            get {
                return ResourceManager.GetString("MENSAJE_EXCEPCION_ARGUMENTO_NULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en parsear un atributo invalido.
        /// </summary>
        internal static string MENSAJE_EXCEPCION_FORMATO_INVALIDO {
            get {
                return ResourceManager.GetString("MENSAJE_EXCEPCION_FORMATO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado en la capa de datos.
        /// </summary>
        internal static string MENSAJE_EXCEPCION_GENERICO {
            get {
                return ResourceManager.GetString("MENSAJE_EXCEPCION_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al parsear un atributo sobrecargado.
        /// </summary>
        internal static string MENSAJE_EXCEPCION_SOBRECARGA {
            get {
                return ResourceManager.GetString("MENSAJE_EXCEPCION_SOBRECARGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uno de los atributos no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error se ha producido una excepcion.
        /// </summary>
        internal static string Mensaje_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error existe una referencia nula.
        /// </summary>
        internal static string Mensaje_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error existe un conflicto con la conexión a la base de datos.
        /// </summary>
        internal static string Mensaje_ExcepcionSql {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saliendo del metodo.
        /// </summary>
        internal static string MENSAJE_SALIDA_LOGGER {
            get {
                return ResourceManager.GetString("MENSAJE_SALIDA_LOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cantidad.
        /// </summary>
        internal static string PARAMETRO_CANTIDAD {
            get {
                return ResourceManager.GetString("PARAMETRO_CANTIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impColor.
        /// </summary>
        internal static string PARAMETRO_COLOR {
            get {
                return ResourceManager.GetString("PARAMETRO_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impDescripcion.
        /// </summary>
        internal static string PARAMETRO_DESCRIPCION {
            get {
                return ResourceManager.GetString("PARAMETRO_DESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estado.
        /// </summary>
        internal static string PARAMETRO_ESTADO_COMPRA {
            get {
                return ResourceManager.GetString("PARAMETRO_ESTADO_COMPRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impEstatus.
        /// </summary>
        internal static string PARAMETRO_ESTATUS {
            get {
                return ResourceManager.GetString("PARAMETRO_ESTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @exito.
        /// </summary>
        internal static string PARAMETRO_EXITO {
            get {
                return ResourceManager.GetString("PARAMETRO_EXITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fecha.
        /// </summary>
        internal static string PARAMETRO_FECHA {
            get {
                return ResourceManager.GetString("PARAMETRO_FECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCompra.
        /// </summary>
        internal static string PARAMETRO_ID_COMPRA {
            get {
                return ResourceManager.GetString("PARAMETRO_ID_COMPRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idPersona.
        /// </summary>
        internal static string PARAMETRO_ID_PERSONA {
            get {
                return ResourceManager.GetString("PARAMETRO_ID_PERSONA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @per_id.
        /// </summary>
        internal static string PARAMETRO_ID_USUARIO {
            get {
                return ResourceManager.GetString("PARAMETRO_ID_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idEvento.
        /// </summary>
        internal static string PARAMETRO_IDEVENTO {
            get {
                return ResourceManager.GetString("PARAMETRO_IDEVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idImplemento.
        /// </summary>
        internal static string PARAMETRO_IDIMPLEMENTO {
            get {
                return ResourceManager.GetString("PARAMETRO_IDIMPLEMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idImplemento.
        /// </summary>
        internal static string PARAMETRO_IDIMPLEMENTO2 {
            get {
                return ResourceManager.GetString("PARAMETRO_IDIMPLEMENTO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idMatricula.
        /// </summary>
        internal static string PARAMETRO_IDMATRICULA {
            get {
                return ResourceManager.GetString("PARAMETRO_IDMATRICULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idMatricula.
        /// </summary>
        internal static string PARAMETRO_IDMATRICULA2 {
            get {
                return ResourceManager.GetString("PARAMETRO_IDMATRICULA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impImagen.
        /// </summary>
        internal static string PARAMETRO_IMAGEN {
            get {
                return ResourceManager.GetString("PARAMETRO_IMAGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @iditem.
        /// </summary>
        internal static string PARAMETRO_ITEM {
            get {
                return ResourceManager.GetString("PARAMETRO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impMarca.
        /// </summary>
        internal static string PARAMETRO_MARCA {
            get {
                return ResourceManager.GetString("PARAMETRO_MARCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impNombre.
        /// </summary>
        internal static string PARAMETRO_NOMBRE {
            get {
                return ResourceManager.GetString("PARAMETRO_NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pago.
        /// </summary>
        internal static string PARAMETRO_PAGO {
            get {
                return ResourceManager.GetString("PARAMETRO_PAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impPrecio.
        /// </summary>
        internal static string PARAMETRO_PRECIO {
            get {
                return ResourceManager.GetString("PARAMETRO_PRECIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @precio.
        /// </summary>
        internal static string PARAMETRO_PRECIO2 {
            get {
                return ResourceManager.GetString("PARAMETRO_PRECIO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impTalla.
        /// </summary>
        internal static string PARAMETRO_TALLA {
            get {
                return ResourceManager.GetString("PARAMETRO_TALLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impTipo.
        /// </summary>
        internal static string PARAMETRO_TIPO {
            get {
                return ResourceManager.GetString("PARAMETRO_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tipoitem.
        /// </summary>
        internal static string PARAMETRO_TIPO_ITEM {
            get {
                return ResourceManager.GetString("PARAMETRO_TIPO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tipoPago.
        /// </summary>
        internal static string PARAMETRO_TIPO_PAGO {
            get {
                return ResourceManager.GetString("PARAMETRO_TIPO_PAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idusuario.
        /// </summary>
        internal static string PARAMETRO_USUARIO {
            get {
                return ResourceManager.GetString("PARAMETRO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eve_id.
        /// </summary>
        internal static string ParamIdEvento {
            get {
                return ResourceManager.GetString("ParamIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @mat_id.
        /// </summary>
        internal static string ParamIdMatricula {
            get {
                return ResourceManager.GetString("ParamIdMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @mat_persona.
        /// </summary>
        internal static string ParamIdPersona {
            get {
                return ResourceManager.GetString("ParamIdPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_AGREGAR_EVENTO_CARRITO.
        /// </summary>
        internal static string PROCEDIMIENTO_AGREGAR_EVENTO_CARRITO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_AGREGAR_EVENTO_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_AGREGAR_MATRICULA_CARRITO.
        /// </summary>
        internal static string PROCEDIMIENTO_AGREGAR_MATRICULA_CARRITO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_AGREGAR_MATRICULA_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_CONSULTAR_EVENTO_ID.
        /// </summary>
        internal static string PROCEDIMIENTO_CONSULTAR_EVENTO_ID {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_CONSULTAR_EVENTO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_CONSULTAR_INVENTARIO_ID.
        /// </summary>
        internal static string PROCEDIMIENTO_CONSULTAR_INVENTARIO_ID {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_CONSULTAR_INVENTARIO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_CONSULTAR_MATRICULA_ID.
        /// </summary>
        internal static string PROCEDIMIENTO_CONSULTAR_MATRICULA_ID {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_CONSULTAR_MATRICULA_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_ELIMINAR_ITEM.
        /// </summary>
        internal static string PROCEDIMIENTO_ELIMINAR_ITEM {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_ELIMINAR_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_MATRICULAS_PAGADAS.
        /// </summary>
        internal static string PROCEDIMIENTO_MATRICULAS_PAGADAS {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_MATRICULAS_PAGADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_MODIFICAR_CANTIDAD_IMPLEMENTO.
        /// </summary>
        internal static string PROCEDIMIENTO_MODIFICAR_CANTIDAD_IMPLEMENTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_MODIFICAR_CANTIDAD_IMPLEMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_REGISTRAR_PAGO.
        /// </summary>
        internal static string PROCEDIMIENTO_REGISTRAR_PAGO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_REGISTRAR_PAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_SELECCIONAR_ID_EVENTO.
        /// </summary>
        internal static string PROCEDIMIENTO_SELECCIONAR_ID_EVENTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_SELECCIONAR_ID_EVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_SELECCIONAR_ID_INVENTARIO.
        /// </summary>
        internal static string PROCEDIMIENTO_SELECCIONAR_ID_INVENTARIO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_SELECCIONAR_ID_INVENTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_SELECCIONAR_ID_MATRICULA.
        /// </summary>
        internal static string PROCEDIMIENTO_SELECCIONAR_ID_MATRICULA {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_SELECCIONAR_ID_MATRICULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_agregarEventoaCarrito.
        /// </summary>
        internal static string StoreProcedureAgregareventoaCarrito {
            get {
                return ResourceManager.GetString("StoreProcedureAgregareventoaCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_AGREGAR_IMPLEMENTO_CARRITO.
        /// </summary>
        internal static string StoreProcedureAgregarinventarioaCarrito {
            get {
                return ResourceManager.GetString("StoreProcedureAgregarinventarioaCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_agregarMatriculaaCarrito.
        /// </summary>
        internal static string StoreProcedureAgregarmatriculaaCarrito {
            get {
                return ResourceManager.GetString("StoreProcedureAgregarmatriculaaCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_detallarEvento.
        /// </summary>
        internal static string StoreProcedureConsultarEventosXId {
            get {
                return ResourceManager.GetString("StoreProcedureConsultarEventosXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_consultarMatriculas.
        /// </summary>
        internal static string StoreProcedureConsultarMatriculas {
            get {
                return ResourceManager.GetString("StoreProcedureConsultarMatriculas", resourceCulture);
            }
        }
    }
}
